import { Service, NavInfo, NavItem, SocialLink, FooterInfo } from "./types";
import {
  faFacebook,
  faXTwitter,
  faInstagram,
  faLinkedinIn,
} from "@fortawesome/free-brands-svg-icons";
import transportation from "../assets/transportation.png";

export const servicesData: Service[] = [
  {
    title: "Construction",
    description:
      "Construction Division has constructed several turnkey projects across the country including civil and electrical projects.",
    image:
      "https://images.unsplash.com/photo-1530639834082-05bafb67fbbe?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "/services/construction",
  },
  {
    title: "Transportation",
    description:
      "Over the years of operations we have acquired fleets of trailers for haulage business and developed an extensive road transportation network.",
    image: transportation,
    link: "/services/transportation",
  },
  {
    title: "Telecoms",
    description:
      "The division is registered with NCC to operate as a telecoms sales outfit for phones, Computers and IT hardware and software.",
    image:
      "https://images.unsplash.com/photo-1681735342773-d452708e87e7?q=80&w=2802&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "/services/telecoms",
  },
  {
    title: "Consults",
    description:
      "This division is mostly engaged as consults to various organizations and also form client's briefs in the development of business proposals.",
    image:
      "https://images.unsplash.com/photo-1633114127824-14b3207d7d74?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "/services/consults",
  },
  {
    title: "Solar Generation",
    description:
      "This division is mostly engaged in the generation, transmitting and distribution of power/energy generated by solar energy.",
    image:
      "https://images.unsplash.com/photo-1637692408593-8229e72427e0?q=80&w=3053&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "/services/solar-generation",
  },
  {
    title: "Gauni Water",
    description:
      "Our Water Division is dedicated to providing premium bottled water, crafted to meet the highest standards of quality and purity",
    image:
      "https://images.unsplash.com/photo-1536939459926-301728717817?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "/services/gauni-water",
  },
];

export const navInfo: NavInfo = {
  address: "Adamawa, Nigeria",
  email: "abdaminltd@gmail.com",
  phone: "+2349123278100",
};

export const navItems: NavItem[] = [
  { name: "Home", link: "/" },
  { name: "About Us", link: "/about-us" },
  { name: "Portfolio", link: "/portfolio" },
  { name: "Services", link: "/services" },
  { name: "Get In Touch", link: "/contact-us" },
];

export const socialLinks: SocialLink[] = [
  {
    label: "LinkedIn",
    icon: faLinkedinIn,
    url: "https://www.linkedin.com/company/abdamin",
  },
  {
    label: "Instagram",
    icon: faInstagram,
    url: "https://www.instagram.com/abdamin",
  },
  {
    label: "Facebook",
    icon: faFacebook,
    url: "https://www.facebook.com/abdamin",
  },
  { label: "Twitter", icon: faXTwitter, url: "https://twitter.com/abdamin" },
];

export const copyRight = `© ${new Date().getFullYear()}. Abdamin International Limited.`;

export const footerInfo: FooterInfo = {
  address: "36, Bank Road, Bekaji, PMB 2106, Jimeta, Adamawa State",
  email: "abdaminltd@gmail.com",
  phone: "+2349123278100",
};
