import { Service, NavInfo, NavItem, SocialLink, FooterInfo } from "./types";
import {
  faFacebook,
  faXTwitter,
  faInstagram,
  faLinkedinIn,
} from "@fortawesome/free-brands-svg-icons";
import transportation from "@/assets/images/transportation.webp";
import construction from "@/assets/images/constuction.webp";
import telecoms from "@/assets/images/telecoms.webp";
import consults from "@/assets/images/consultation.webp";
import solarGeneration from "@/assets/images/solar-generation.webp";
import gauniWater from "@/assets/images/gauni-water.webp";

export const servicesData: Service[] = [
  {
    title: "Construction",
    description:
      "Construction Division has constructed several turnkey projects across the country including civil and electrical projects.",
    image: construction,
    link: "/services/construction",
  },
  {
    title: "Transportation",
    description:
      "Over the years of operations we have acquired fleets of trailers for haulage business and developed an extensive road transportation network.",
    image: transportation,
    link: "/services/transportation",
  },
  {
    title: "Telecoms",
    description:
      "The division is registered with NCC to operate as a telecoms sales outfit for phones, Computers and IT hardware and software.",
    image: telecoms,
    link: "/services/telecoms",
  },
  {
    title: "Consults",
    description:
      "This division is mostly engaged as consults to various organizations and also form client's briefs in the development of business proposals.",
    image: consults,
    link: "/services/consults",
  },
  {
    title: "Solar Generation",
    description:
      "This division is mostly engaged in the generation, transmitting and distribution of power/energy generated by solar energy.",
    image: solarGeneration,
    link: "/services/solar-generation",
  },
  {
    title: "Gauni Water",
    description:
      "Our Water Division is dedicated to providing premium bottled water, crafted to meet the highest standards of quality and purity",
    image: gauniWater,
    link: "/services/gauni-water",
  },
];

export const navInfo: NavInfo = {
  address: "Adamawa, Nigeria",
  email: "abdaminltd@gmail.com",
  phone: "+2349123278100",
};

export const navItems: NavItem[] = [
  { name: "Home", link: "/" },
  { name: "About Us", link: "/about-us" },
  { name: "Portfolio", link: "/portfolio" },
  {
    name: "Services",
    link: "/services",
    subItems: [
      { name: "Construction", link: "/services/construction" },
      { name: "Transportation", link: "/services/transportation" },
      { name: "Telecoms", link: "/services/telecoms" },
      { name: "Consults", link: "/services/consults" },
      { name: "Solar Generation", link: "/services/solar-generation" },
      { name: "Gauni Water", link: "/services/gauni-water" },
    ],
  },
  { name: "Get In Touch", link: "/get-in-touch" },
];

export const socialLinks: SocialLink[] = [
  {
    label: "LinkedIn",
    icon: faLinkedinIn,
    url: "#",
  },
  {
    label: "Instagram",
    icon: faInstagram,
    url: "#",
  },
  {
    label: "Facebook",
    icon: faFacebook,
    url: "#",
  },
  { label: "Twitter", icon: faXTwitter, url: "#" },
];

export const copyRight = `© ${new Date().getFullYear()}. Abdamin International Limited.`;

export const footerInfo: FooterInfo = {
  address: "36, Bank Road, Bekaji, PMB 2106, Jimeta, Adamawa State",
  email: "abdaminltd@gmail.com",
  phone: "+2349123278100",
};
